name: Java Run

on:
  push:
    branches:
      - main # Cambia 'main' por el nombre de tu rama principal si es diferente

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run Java project
        run: java -cp target/<practica_logica>.jar com.mycompany.practica_logica.Practica_logica
